apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: controller
  name: api-ingress-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: api-ingress-class
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: api-ingress-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: {{ .Values.port }}